import jsPDF from "jspdf";

interface ReportData {
    student_name: string | null;
    student_id_code?: string | null;
    risk_score: number;
    risk_level: string;
    created_at: string;
    top_factors: { label: string; level: string; delta: number; description: string }[];
    interventions: { title: string; description: string }[];
    professor?: { full_name: string; department: string } | null;
}

export function exportAssessmentPDF(d: ReportData) {
    const doc = new jsPDF({ unit: "pt", format: "letter" });
    const W = doc.internal.pageSize.getWidth();
    let y = 56;

    doc.setFillColor(37, 99, 235);
    doc.rect(0, 0, W, 64, "F");
    doc.setTextColor(255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(20);
    doc.text("FAILSAFE", 40, 32);
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text("Early Intervention System — Risk Assessment Report", 40, 50);

    y = 100;
    doc.setTextColor(20);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.text(d.student_id_code ? `Student #${d.student_id_code}` : "Anonymous Student", 40, y);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(110);
    y += 16;
    doc.text(
        `${d.student_id_code ? `ID ${d.student_id_code} • ` : ""}Assessed ${new Date(d.created_at).toLocaleString()}`,
        40, y,
    );
    if (d.professor) {
        y += 14;
        doc.text(`Reviewed by ${d.professor.full_name} — ${d.professor.department}`, 40, y);
    }

    // Risk box
    y += 28;
    const lvlColor: [number, number, number] =
        d.risk_level === "high" ? [220, 38, 38] : d.risk_level === "medium" ? [217, 119, 6] : [22, 163, 74];
    doc.setDrawColor(229);
    doc.setFillColor(248, 250, 252);
    doc.roundedRect(40, y, W - 80, 70, 8, 8, "FD");
    doc.setTextColor(...lvlColor);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(28);
    doc.text(`${d.risk_score.toFixed(1)}%`, 60, y + 44);
    doc.setFontSize(11);
    doc.text(d.risk_level.toUpperCase() + " RISK", 60, y + 60);
    doc.setTextColor(60);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text("Calculated Risk Score", 200, y + 28);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text(
        d.risk_level === "high"
            ? "Student is highly likely to fail academically."
            : d.risk_level === "medium"
                ? "Student requires monitoring and support."
                : "Student is on track academically.",
        200, y + 48,
    );
    y += 96;

    // Factors
    doc.setTextColor(20);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.text("Key Risk Factors", 40, y);
    y += 16;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    for (const f of d.top_factors.slice(0, 6)) {
        doc.setTextColor(20);
        doc.setFont("helvetica", "bold");
        doc.text(`${f.label}`, 50, y);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(110);
        doc.text(f.description, 180, y);
        doc.setTextColor(...(f.level === "HIGH RISK" ? [220, 38, 38] : f.level === "MEDIUM RISK" ? [217, 119, 6] : [22, 163, 74]) as [number, number, number]);
        doc.text(`${f.delta >= 0 ? "+" : ""}${f.delta.toFixed(1)}%`, W - 80, y);
        y += 18;
    }

    // Interventions
    y += 12;
    doc.setTextColor(20);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.text("Suggested Interventions", 40, y);
    y += 16;
    d.interventions.forEach((iv, i) => {
        doc.setFont("helvetica", "bold");
        doc.setFontSize(11);
        doc.setTextColor(20);
        doc.text(`${i + 1}. ${iv.title}`, 50, y);
        y += 14;
        doc.setFont("helvetica", "normal");
        doc.setFontSize(10);
        doc.setTextColor(90);
        const lines = doc.splitTextToSize(iv.description, W - 100);
        doc.text(lines, 50, y);
        y += lines.length * 12 + 8;
    });

    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(
        "Generated by FAILSAFE • Confidential — for educational professional use only",
        40, doc.internal.pageSize.getHeight() - 24,
    );

    doc.save(`FAILSAFE_${(d.student_id_code ?? "assessment").replace(/\s+/g, "_")}.pdf`);
}
